#!/usr/bin/env perl
# PODNAME: $1
# ABSTRACT: $2

=head1 NAME

$1

=head1 SYNOPSIS

    > $1 ..options..

    to get full help use
    > $1 --help

=head1 DESCRIPTION

$2

=cut

#
# (c) yourname, your@email.address.com
# this code is released under the Perl Artistic License

use 5.10.0 ;
use strict ;
use warnings ;
use App::Basis ;
use Path::Tiny ;
use App::Basis::ConvertText2::Support ;

# -----------------------------------------------------------------------------
# main

my %opt = init_app(
    help_text => "$2",
    options   => {
        'has_content=i' => 'show that there is something echoed in STDIN',
        'doc_ref=s'     => 'name of the document, this is being called from',
        'cachedir=s' => {desc => 'Where to store temp files', required => 1},
        "linenum=i" => "Linenumber in the file this construct used on, useful for error reporting",
        'verbose|v' => 'Verbose for debugging',
    },
) ;
my ($content, $output) ;
# readin the content
if ( $opt{has_content} ) {
    $content = do { local $/ ; <STDIN> } ;
    chomp $content ;

    # if we need to check a cache for this item, we need a sig first
    my $sig = create_sig( $content, \%opt ) ;

}


# be careful how output happens, in case its in-line in a .table or something
# so no \n at the end of the line!
print $output ;




