#!/usr/bin/env perl
# PODNAME: required
# ABSTRACT: add icon or text to show something is a required thing

=head1 NAME

required

=head1 SYNOPSIS

    > required ..options..

    to get full help use
    > required --help

=head1 DESCRIPTION

add icon or text to show something is a required thing

=cut

#
# (c) yourname, your@email.address.com
# this code is released under the Perl Artistic License

use 5.10.0 ;
use strict ;
use warnings ;
use App::Basis ;

# -----------------------------------------------------------------------------
# main

my %opt = init_app(
    help_text => "add icon or text to show something is a required thing",
    options   => {
        'has_content=i' => 'add icon or text to show something is a required thing',
        'doc_ref=s'     => 'name of the document, this is being called from',
        'cachedir=s' => {desc => 'Where to store temp files', required => 1},
        "linenum=i" => "Linenumber in the file this construct used on, useful for error reporting",
        'verbose|v' => 'Verbose for debugging',
    },
) ;
my ($content, $output) ;
# readin the content
# if ( $opt{has_content} ) {
#     $content = do { local $/ ; <STDIN> } ;
#     chomp $content ;
# }

$output = "<font size=-1><c:green700>:mi:check_box:required</c></font>" ;

# be careful how output happens, in case its in-line in a .table or something
# so no \n at the end of the line!
print $output ;




